name: Amazon Price Tracker

on:
  schedule:
    # Run daily at 12 PM and 6 PM IST (6:30 and 12:30 in UTC)
    - cron: '30 6,12 * * *'

jobs:
  price-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4

      - name: Run Amazon Price Tracker
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          HEADERS: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36'
        run: |
          python availability-check.py
